#!/usr/bin/env bash

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}
# increase trackpoint sensitivity on Lenovo Keyboard
# xinput set-prop "PS/2 Generic Mouse" "Device Accel Constant Deceleration" 0.5

export QT_QPA_PLATFORMTHEME=qt5ct

feh --bg-scale ~/Pictures/Wallpapers/geometry.jpg
run picom --config ~/.config/compton/compton.conf
run albert
run pasystray --notify=sink_default
run copyq
run nm-applet
run guake
# run indicator-kdeconnect
run stalonetray
run qxkb
run slack
run telegram-desktop
run blueman-tray
